spring:
  application:
    name: musinsa-api
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul
        show_sql: true
        format_sql: false
#        globally_quoted_identifiers: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
    show-sql: true
  mvc:
    format:
      date-time: iso-offset
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  paths-to-match: /api/**