spring:
  application:
    name: community-api
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul
        show_sql: true
        format_sql: false
#        globally_quoted_identifiers: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true

    show-sql: true
    dialect:
      mysql: org.hibernate.dialect.MySQL8Dialect
  mvc:
    format:
      date-time: iso-offset
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
    #url: 'jdbc:h2:~/test'    # H2 DB 연결 주소 (Embedded Mode)
    username: username        # H2 DB 접속 ID (사용자 지정)
    password: password        # H2 DB 접속 PW (사용자 지정)
    # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console
#  sql:
#    init: # application 실행시 sql 실행
#      username: sa
#      password:
#      schema-locations: classpath*:db/schema.sql
#      data-locations: classpath*:db/data.sql